### ISSUE TITLE
subdivide the messages

### ISSUE THREAD

**Issue by vinniec** [knadh/tg-archive#119]
I'm saving the content of a group with your program, in truth I'm not done yet, however the goal afterward is to catalog part of the messages to filter them.

Now it's not like I have much idea how to do it, looking at the code of tg-archive I understand that maybe the way would be to add a table to the db with tags and populate it (however I don't know yet what would be a practical way) and modify the template so that there are sections where there are only tagged messages.

It's not like I know much about it, would you have any advice?
Thanks!

**Comment by vinniec** [comment]
ok i found this issue https://github.com/knadh/tg-archive/issues/99 , is there any way to avoid re-downloading the media while changing the date to utc?

**Comment by vinniec** [comment]
I tried again by disabling the media to quickly download the messages and try to do build (I noticed that there is no external reference to the media in the database, I hope I won't have to re-download it again) but it gives again another error:

```
tg-archive --build
2023-11-06 01:38:58,294: building site
Traceback (most recent call last):
  File "G:\fla\thonny\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "G:\fla\thonny\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "G:\fla\thonny\Scripts\tg-archive.exe\__main__.py", line 7, in <module>
  File "G:\fla\thonny\lib\site-packages\tgarchive\__init__.py", line 161, in main
    b.build()
  File "G:\fla\thonny\lib\site-packages\tgarchive\build.py", line 100, in build
    self._build_rss(rss_entries, "index.rss", "index.atom")
  File "G:\fla\thonny\lib\site-packages\tgarchive\build.py", line 154, in _build_rss
    media_mime = magic.from_file(media_path, mime=True)
  File "G:\fla\thonny\lib\site-packages\magic\magic.py", line 135, in from_file
    return m.from_file(filename)
  File "G:\fla\thonny\lib\site-packages\magic\magic.py", line 85, in from_file
    with open(filename):
OSError: [Errno 22] Invalid argument: 'media/https://www.youtube.com/watch?v=Eb2m5ATyGEs'
```
