### ISSUE TITLE
error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by Kizuna-Meraki** [knadh/tg-archive#129]
I used the "`pip3 install tg-archive`" to install, but got this error / these errors:

```
Collecting tg-archive
  Using cached tg-archive-1.1.3.tar.gz (28 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/vg/1rplx7gs1fg3scppn49c_vm40000gp/T/pip-install-6j1tgm6n/tg-archive_7fca1255502241658369350a782f07e7/setup.py", line 5, in <module>
          from tgarchive import __version__
        File "/private/var/folders/vg/1rplx7gs1fg3scppn49c_vm40000gp/T/pip-install-6j1tgm6n/tg-archive_7fca1255502241658369350a782f07e7/tgarchive/__init__.py", line 6, in <module>
          import yaml
      ModuleNotFoundError: No module named 'yaml'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by Kizuna-Meraki** [comment]
I fixed the problem by looking at the list of 8 requirements. In the order listed, I installed each component individually. After installing all 8 prerequisites, I ran pip3 install tg-archive and it installed without errors. (So, of the 8 things I installed, I do not know which one fixed the error.)

This is the output from the successful install:

```
pip3 install tg-archive

Collecting tg-archive
  Using cached tg-archive-1.1.3.tar.gz (28 kB)
  Preparing metadata (setup.py) ... done
Collecting telethon==1.29.3 (from tg-archive)
  Downloading Telethon-1.29.3.tar.gz (548 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 548.9/548.9 kB 7.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: jinja2>=2.11.3 in /usr/local/lib/python3.10/site-packages (from tg-archive) (3.1.3)
Requirement already satisfied: PyYAML>=5.4.1 in /usr/local/lib/python3.10/site-packages (from tg-archive) (6.0.1)
Collecting cryptg==0.2.post2 (from tg-archive)
  Downloading cryptg-0.2.post2.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Pillow>=8.3.2 in /usr/local/lib/python3.10/site-packages (from tg-archive) (10.2.0)
Requirement already satisfied: feedgen>=0.9.0 in /usr/local/lib/python3.10/site-packages (from tg-archive) (1.0.0)
Requirement already satisfied: python-magic>=0.4.24 in /usr/local/lib/python3.10/site-packages (from tg-archive) (0.4.27)
Requirement already satisfied: pytz>=2020.5 in /usr/local/lib/python3.10/site-packages (from tg-archive) (2024.1)
Collecting cffi>=1.0.0 (from cryptg==0.2.post2->tg-archive)
  Using cached cffi-1.16.0-cp310-cp310-macosx_10_9_x86_64.whl.metadata (1.5 kB)
Collecting pycparser (from cryptg==0.2.post2->tg-archive)
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Requirement already satisfied: pyaes in /usr/local/lib/python3.10/site-packages (from telethon==1.29.3->tg-archive) (1.6.1)
Requirement already satisfied: rsa in /usr/local/lib/python3.10/site-packages (from telethon==1.29.3->tg-archive) (4.9)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/site-packages (from feedgen>=0.9.0->tg-archive) (5.1.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/site-packages (from feedgen>=0.9.0->tg-archive) (2.8.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/site-packages (from jinja2>=2.11.3->tg-archive) (2.1.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/site-packages (from python-dateutil->feedgen>=0.9.0->tg-archive) (1.16.0)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python3.10/site-packages (from rsa->telethon==1.29.3->tg-archive) (0.5.1)
Using cached cffi-1.16.0-cp310-cp310-macosx_10_9_x86_64.whl (182 kB)
Building wheels for collected packages: tg-archive, cryptg, telethon
  Building wheel for tg-archive (setup.py) ... done
  Created wheel for tg-archive: filename=tg_archive-1.1.3-py3-none-any.whl size=29935 sha256=8f196f93aa0b4ad5248d243810cbbd972947f7c2ddcde30f6bdbf7faa45c508f
  Stored in directory: /Users/kitzume/Library/Caches/pip/wheels/aa/ed/78/5c2a976fc88541003e59fb239c85bcfe1cdd4a343e152d19b3
  Building wheel for cryptg (setup.py) ... done
  Created wheel for cryptg: filename=cryptg-0.2.post2-cp310-cp310-macosx_13_0_x86_64.whl size=11323 sha256=f7f4b2b76c632a590db7ac5a9782db8ead9e3dceb4279f7fbcd2c32b9c6b27e4
  Stored in directory: /Users/kitzume/Library/Caches/pip/wheels/4f/05/ae/f656a72c6b4b0a246ffae466ee431e51d8303094e319cdab12
  Building wheel for telethon (pyproject.toml) ... done
  Created wheel for telethon: filename=Telethon-1.29.3-py3-none-any.whl size=619118 sha256=5f73c293e86105c2e7a02f6dabd0a6d7d0c5fa599d40aed61eceb799e6bcf343
  Stored in directory: /Users/kitzume/Library/Caches/pip/wheels/91/20/3d/a936adecac5192dd8ad23ff121636189800c12c91410a839c5
Successfully built tg-archive cryptg telethon
Installing collected packages: pycparser, telethon, cffi, cryptg, tg-archive
  Attempting uninstall: telethon
    Found existing installation: Telethon 1.34.0
    Uninstalling Telethon-1.34.0:
      Successfully uninstalled Telethon-1.34.0
  Attempting uninstall: cryptg
    Found existing installation: cryptg 0.4.0
    Uninstalling cryptg-0.4.0:
      Successfully uninstalled cryptg-0.4.0
Successfully installed cffi-1.16.0 cryptg-0.2.post2 pycparser-2.21 telethon-1.29.3 tg-archive-1.1.3
```
