### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'collections.OrderedDict object' has no attribute 

### ISSUE THREAD

**Issue by Kizuna-Meraki** [knadh/tg-archive#130]
After successfully creating, syncing and building 2 groups, I got this when archiving the third group.

tg-archive --build

2024-02-12 19:04:44,734: building site
Traceback (most recent call last):
  File "/usr/local/bin/tg-archive", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/tgarchive/__init__.py", line 161, in main
    b.build()
  File "/usr/local/lib/python3.10/site-packages/tgarchive/build.py", line 87, in build
    self._render_page(messages, month, dayline,
  File "/usr/local/lib/python3.10/site-packages/tgarchive/build.py", line 116, in _render_page
    html = self.template.render(config=self.config,
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 90, in top-level template code
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'collections.OrderedDict object' has no attribute '2016-12-02'

**Comment by Kizuna-Meraki** [comment]
Another group failed during tg-archive --build with the same error message. 


```
tg-archive --build
2024-02-12 20:02:19,652: building site
Traceback (most recent call last):
  File "/usr/local/bin/tg-archive", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/tgarchive/__init__.py", line 161, in main
    b.build()
  File "/usr/local/lib/python3.10/site-packages/tgarchive/build.py", line 87, in build
    self._render_page(messages, month, dayline,
  File "/usr/local/lib/python3.10/site-packages/tgarchive/build.py", line 116, in _render_page
    html = self.template.render(config=self.config,
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 90, in top-level template code
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'collections.OrderedDict object' has no attribute '2017-09-22'

```

**Comment by VAny6661** [comment]
In db.py try change
```
 cur.execute("""
            SELECT strftime('%Y-%m-%d 00:00:00', date) as "[timestamp]",
            COUNT(*) FROM messages AS count
            GROUP BY strftime('%Y-%m', date) ORDER BY date
        """)
```
to
```
SELECT strftime('%Y-%m-%d %H:%M:%S', date) as "[timestamp]",
            COUNT(*) FROM messages AS count
            GROUP BY strftime('%Y-%m', date) ORDER BY date
```
or just do not change standart timezone in config.yaml
If not help, you can try answer from [this](https://github.com/knadh/tg-archive/issues/99) issue

**Comment by Pepepy** [comment]
Muchas Gracias, esto soluciona completamente el problema.

> En db.py (en get_timeline y get_dayline) intente cambiar
> 
> ```
>  cur.execute("""
>             SELECT strftime('%Y-%m-%d 00:00:00', date) as "[timestamp]",
>             COUNT(*) FROM messages AS count
>             GROUP BY strftime('%Y-%m', date) ORDER BY date
>         """)
> ```
> 
> a
> 
> ```
> cur.execute("""
>             SELECT strftime('%Y-%m-%d %H:%M:%S', date) as "[timestamp]",
>             COUNT(*) FROM messages AS count
>             GROUP BY strftime('%Y-%m', date) ORDER BY date
>              """)
> ```
> 
> o simplemente no cambie la zona horaria estándar en config.yaml Si no ayuda, puede intentar responder a [este](https://github.com/knadh/tg-archive/issues/99) problema

**Comment by zv09** [comment]
same #161 and inside #99 seems some dev asking for possible solve

so let's push issues, notices and updates to https://github.com/knadh/tg-archive/issues/99 even there are some movement is exist...
otherwise we will report the same issues again and again and fixing that bug for years...
