### ISSUE TITLE
Sync failes at specific message, AttributeError: 'MessageReplyStoryHeader' object has no attribute 'reply_to_msg_id'

### ISSUE THREAD

**Issue by subhead** [knadh/tg-archive#150]
Hello,

i try to sync a private chat and i recieve an error and the sync stops at the specific message. The message is a normale text message without images, links or whatever else can be included. 

Is there a way to skip a failed message and continue with the sync of the following messages? 

`2024-12-18 12:37:53,849: cryptg detected, it will be used for encryption
2024-12-18 12:37:54,064: starting Telegram sync (batch_size=2000, limit=0, wait=5, mode=standard)
2024-12-18 12:37:54,283: Connecting to 149.154.167.51:443/TcpFull...
2024-12-18 12:37:54,323: Connection to 149.154.167.51:443/TcpFull complete!
2024-12-18 12:37:54,602: fetching from last message id=84652 (2024-09-09 00:00:00)
Traceback (most recent call last):
  File "E:\Dev\telegram\.venv-win\Scripts\tg-archive-script.py", line 33, in <module>
    sys.exit(load_entry_point('tg-archive==1.2.2', 'console_scripts', 'tg-archive')())
  File "E:\Dev\telegram\.venv-win\lib\site-packages\tgarchive\__init__.py", line 142, in main
    s.sync(args.id, args.from_id)
  File "E:\Dev\telegram\.venv-win\lib\site-packages\tgarchive\sync.py", line 56, in sync
    for m in self._get_messages(group_id,
  File "E:\Dev\telegram\.venv-win\lib\site-packages\tgarchive\sync.py", line 184, in _get_messages
    reply_to=m.reply_to_msg_id if m.reply_to and m.reply_to.reply_to_msg_id else None,
AttributeError: 'MessageReplyStoryHeader' object has no attribute 'reply_to_msg_id'`

**Comment by zv09** [comment]
the same for `--sync` a private chat: 

```
2025-07-27 18:17:37,425: downloading media #99648
Traceback (most recent call last):
  File "/Users/user/Library/Python/3.12/bin/tg-archive", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/user/Library/Python/3.12/lib/python/site-packages/tgarchive/__init__.py", line 142, in main
    s.sync(args.id, args.from_id)
  File "/Users/user/Library/Python/3.12/lib/python/site-packages/tgarchive/sync.py", line 56, in sync
    for m in self._get_messages(group_id,
  File "/Users/user/Library/Python/3.12/lib/python/site-packages/tgarchive/sync.py", line 184, in _get_messages
    reply_to=m.reply_to_msg_id if m.reply_to and m.reply_to.reply_to_msg_id else None,
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MessageReplyStoryHeader' object has no attribute 'reply_to_msg_id'
```
