### ISSUE TITLE
'NoneType' object has no attribute 'mime_type'

### ISSUE THREAD

**Issue by ilyailya** [knadh/tg-archive#16]
Hi folks!

I'm trying to sync a one-to-one chat and see this error:

```
2021-05-24 17:34:12,013: downloading media #1122666
2021-05-24 17:34:12,015: Starting direct file download in chunks of 131072 at 0, stride 131072
Traceback (most recent call last):
  File "/usr/local/bin/tg-archive", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/tgarchive/__init__.py", line 112, in main
    Sync(cfg, args.session, db.DB(args.data)).sync(args.id)
  File "/usr/local/lib/python3.7/site-packages/tgarchive/sync.py", line 59, in sync
    ids=ids):
  File "/usr/local/lib/python3.7/site-packages/tgarchive/sync.py", line 112, in _get_messages
    m.media.document.mime_type == "application/x-tgsticker":
AttributeError: 'NoneType' object has no attribute 'mime_type'
```

**Comment by knadh** [comment]
This is published in `v0.3.5`. You can do a pip upgrade.
