### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by cloakedch** [knadh/tg-archive#19]
Hi

Just tried tg-archive with a random group and stumbled upon the following error:

```
2021-05-27 11:49:19,763: error downloading avatar: #123456789: cannot identify image file <_io.BytesIO object at 0x6af3b1758900>
Traceback (most recent call last):
  File "/usr/local/bin/tg-archive", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/tgarchive/__init__.py", line 112, in main
    Sync(cfg, args.session, db.DB(args.data)).sync(args.id)
  File "/usr/local/lib/python3.9/site-packages/tgarchive/sync.py", line 60, in sync
    for m in self._get_messages(group_id,
  File "/usr/local/lib/python3.9/site-packages/tgarchive/sync.py", line 121, in _get_messages
    med = self._make_poll(m)
  File "/usr/local/lib/python3.9/site-packages/tgarchive/sync.py", line 182, in _make_poll
    for i, r in enumerate(msg.media.results.results):
TypeError: 'NoneType' object is not iterable
```

Any idea what's going on?

**Comment by knadh** [comment]
Looks like it's failing on checking poll results. The API is quite cryptic and hard to test on all these edge cases. I've added a check for this particular error. Can you upgrade to `v0.3.6` and retry?

**Comment by cloakedch** [comment]
Thanks, it works now.
Any chance to push it to PyPi?

**Comment by knadh** [comment]
`v0.3.6` is already on PyPi. Thanks.

**Comment by cloakedch** [comment]
Sorry did not see that. Thanks!
