### ISSUE TITLE
Unicode Error

### ISSUE THREAD

**Issue by Th3Prim3** [knadh/tg-archive#22]
When building website, receive the following error:

```Traceback (most recent call last):

  File "C:\Users\PycharmProjects\vsett_backup\venv2\Scripts\tg-archive-script.py", line 33, in <module>
    sys.exit(load_entry_point('tg-archive==0.3.4', 'console_scripts', 'tg-archive')())
  File "c:\users\pycharmprojects\vsett_backup\venv2\lib\site-packages\tgarchive\__init__.py", line 126, in main
    b.build()
  File "c:\users\pycharmprojects\vsett_backup\venv2\lib\site-packages\tgarchive\build.py", line 83, in build
    self._render_page(messages, month, dayline,
  File "c:\users\pycharmprojects\vsett_backup\venv2\lib\site-packages\tgarchive\build.py", line 117, in _render_page
    f.write(html)
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f923' in position 12123: character maps to <undefined>
```

This seems to be resolved by editing line 116 in build.py to include **encoding='utf-8'** after "w".

**Comment by knadh** [comment]
This was already in the codebase but wasn't released. Release `v0.3.7` that incorporates this. You can do a pip update now.
