### ISSUE TITLE
sqlite3.OperationalError: near "ON": syntax error

### ISSUE THREAD

**Issue by Ikarushka** [knadh/tg-archive#23]
When I run **tg-archive --sync** I get the error:
```
Traceback (most recent call last):
  File "/usr/local/bin/tg-archive", line 11, in <module>
    sys.exit(main())
 File "/usr/local/lib/python3.6/dist-packages/tgarchive/__init__.py", line 119, in main
    Sync(cfg, args.session, DB(args.data)).sync(args.id)
 File "/usr/local/lib/python3.6/dist-packages/tgarchive/sync.py", line 69, in sync
    self.db.insert_user(m.user)
 File "/usr/local/lib/python3.6/dist-packages/tgarchive/db.py", line 174, in insert_user
    """, (u.id, u.username, u.first_name, u.last_name, " ".join(u.tags), u.avatar))
sqlite3.OperationalError: near "ON": syntax error
```
Maybe I was wrong somewhere with the configuration or is it a bug in the code?

**Comment by knadh** [comment]
Looks like an SQLite issue. What version of SQLite do you have installed?

```shell
$ python3 -c "import sqlite3; print(sqlite3.sqlite_version)"
3.34.1
```

**Comment by Ikarushka** [comment]
Hi. I have 3.22.0. Should I update SQLite?

**Comment by knadh** [comment]
Please try upgrading. I think this is to do with SQLite version compatibility. It shouldn't throw a syntax error otherwise.
