### ISSUE TITLE
Loosen version requirements

### ISSUE THREAD

**Issue by Farzat07** [knadh/tg-archive#39]
When running `tg-archive -b` on Arch this error occurs:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Pillow 8.4.0 (/usr/lib/python3.9/site-packages), Requirement.parse('Pillow==8.3.2'), {'tg-archive'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tg-archive", line 33, in <module>
    sys.exit(load_entry_point('tg-archive==0.5.1', 'console_scripts', 'tg-archive')())
  File "/usr/lib/python3.9/site-packages/tgarchive/__init__.py", line 138, in main
    from .build import Build
  File "/usr/lib/python3.9/site-packages/tgarchive/build.py", line 5, in <module>
    import pkg_resources
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Pillow==8.3.2' distribution was not found and is required by tg-archive
```

Running `tg-archive -s` though works perfectly.

Package from which tg-archive was installed: https://aur.archlinux.org/packages/tg-archive-git/
Version of Pillow installed: 8.4.0

Maybe the version requirements should be relaxed a bit? For example by specifying `Pillow>=8.3.2` instead. This should help support package installation on rolling release systems.

**Comment by knadh** [comment]
Yup, makes sense. Done.
