### ISSUE TITLE
Sync private group

### ISSUE THREAD

**Issue by ilyailya** [knadh/tg-archive#5]
Hey, I'm trying to sync a private group, and seeing some issues. Private groups doesn't have public handle like `@group_name`.
I've tried to retrieve a group id from the telegram web version:
1) Open chat in web.telegram.org
2) Link should look like https://web.telegram.org/#/im?p=sXXXXXXXXXX_YYYYYYYYYYYYYYYYYYYY
3) Group ids usually look like `-100XXXXXXXXXX`.

I put that id into config but it crashes. I tried without `-100` prefix and also seeing the crash.

Here is the stacktrace:

```
2021-03-22 15:10:10,754: starting Telegram sync (batch_size=2000, limit=0, wait=5)
2021-03-22 15:10:10,774: Connecting to 149.154.167.51:443/TcpFull...
2021-03-22 15:10:10,826: Connection to 149.154.167.51:443/TcpFull complete!
Traceback (most recent call last):
  File "/usr/local/bin/tg-archive", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/tgarchive/__init__.py", line 112, in main
    Sync(cfg, args.session, db.DB(args.data)).sync(args.id)
  File "/usr/local/lib/python3.7/site-packages/tgarchive/sync.py", line 59, in sync
    ids=ids):
  File "/usr/local/lib/python3.7/site-packages/tgarchive/sync.py", line 101, in _get_messages
    reverse=True):
  File "/usr/local/lib/python3.7/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/telethon/client/messages.py", line 574, in get_messages
    return await it.collect()
  File "/usr/local/lib/python3.7/site-packages/telethon/requestiter.py", line 113, in collect
    async for message in self:
  File "/usr/local/lib/python3.7/site-packages/telethon/requestiter.py", line 58, in __anext__
    if await self._init(**self.kwargs):
  File "/usr/local/lib/python3.7/site-packages/telethon/client/messages.py", line 26, in _init
    self.entity = await self.client.get_input_entity(entity)
  File "/usr/local/lib/python3.7/site-packages/telethon/client/users.py", line 432, in get_input_entity
    await self._get_entity_from_string(peer))
  File "/usr/local/lib/python3.7/site-packages/telethon/client/users.py", line 570, in _get_entity_from_string
    'Cannot find any entity corresponding to "{}"'.format(string)
ValueError: Cannot find any entity corresponding to "<redacted_group_id>"
```

**Comment by ilyailya** [comment]
I also tried to retrieve ID using telethon:
```python
client = TelegramClient(...)
dialog = client.get_dialogs[x] # x is the index of a group chat
dialog.entity.id # doesn't work
dialog.access_hash # also doesn't work
```

**Comment by knadh** [comment]
I am not sure how private groups work with Telethon. Checked a bunch of Telethon issues and couldn't find anything helpful.

**Comment by Lonami** [comment]
tg-archive should probably call `iter_dialogs` once to fill its cache, then it will find the ID. If it's not in cache, Telethon doesn't know where to look (but we do, it's in the dialogs; that's why it's up to the user code to find the ID). This is explained in more detail in the [Entities — Telethon documentation](https://docs.telethon.dev/en/latest/concepts/entities.html).

**Comment by caco3** [comment]
Thanks, this fix works for my private channel

**Comment by caco3** [comment]
The fix works for my private channel
