### ISSUE TITLE
sqlite3.OperationalError

### ISSUE THREAD

**Issue by igoros777** [knadh/tg-archive#55]
I am getting the following error when running tg-archive --sync 

`# tg-archive --sync
2022-03-03 08:49:22,650: cryptg detected, it will be used for encryption
2022-03-03 08:49:22,901: starting Telegram sync (batch_size=2000, limit=0, wait=5, mode=standard)
2022-03-03 08:49:23,122: Connecting to 149.154.175.60:443/TcpFull...
2022-03-03 08:49:23,165: Connection to 149.154.175.60:443/TcpFull complete!
2022-03-03 08:49:23,629: fetching from last message id=0 (None)
Traceback (most recent call last):
  File "/usr/local/bin/tg-archive", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/tgarchive/__init__.py", line 132, in main
    s.sync(args.id, args.from_id)
  File "/usr/local/lib/python3.6/dist-packages/tgarchive/sync.py", line 65, in sync
    self.db.insert_user(m.user)
  File "/usr/local/lib/python3.6/dist-packages/tgarchive/db.py", line 174, in insert_user
    """, (u.id, u.username, u.first_name, u.last_name, " ".join(u.tags), u.avatar))
sqlite3.OperationalError: near "ON": syntax error`

**Comment by knadh** [comment]
Please see this https://github.com/knadh/tg-archive/issues/23
