### ISSUE TITLE
tg-archive --sync

### ISSUE THREAD

**Issue by yechoo0321** [knadh/tg-archive#56]
2022-03-19 17:16:35,013: Failed to load SSL library: <class 'OSError'> (no library called "ssl" found)
2022-03-19 17:16:35,015: cryptg detected, it will be used for encryption
Traceback (most recent call last):
  File "C:\Users\Chy\AppData\Local\Programs\Python\Python38\Scripts\tg-archive-script.py", line 33, in <module>
    sys.exit(load_entry_point('tg-archive==0.5.4', 'console_scripts', 'tg-archive')())
  File "C:\Users\Chy\AppData\Local\Programs\Python\Python38\lib\site-packages\tg_archive-0.5.4-py3.8.egg\tgarchive\__init__.py", line 124, in main
    cfg = get_config(args.config)
  File "C:\Users\Chy\AppData\Local\Programs\Python\Python38\lib\site-packages\tg_archive-0.5.4-py3.8.egg\tgarchive\__init__.py", line 46, in get_config
    with open(path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'

**Comment by benborges** [comment]
that happens if you run the tg command outside of the "my site" folder, where the config file is residing ?
