### ISSUE TITLE
AttributeError: 'ChannelForbidden' object has no attribute 'scam'

### ISSUE THREAD

**Issue by zoghal** [knadh/tg-archive#71]
hi
the script when running and downloading user avatar, it shows the follwing error.

```
2022-06-24 17:40:50,837: downloading avatar #1427147022
2022-06-24 17:40:50,838: user has no avatar #1427147022
2022-06-24 17:40:50,839: downloading avatar #1470989980
2022-06-24 17:40:50,839: user has no avatar #1470989980
Traceback (most recent call last):
  File "/usr/local/bin/tg-archive", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/tgarchive/__init__.py", line 130, in main
    s.sync(args.id, args.from_id)
  File "/usr/local/lib/python3.8/dist-packages/tgarchive/sync.py", line 56, in sync
    for m in self._get_messages(group_id,
  File "/usr/local/lib/python3.8/dist-packages/tgarchive/sync.py", line 165, in _get_messages
    user=self._get_user(m.sender),
  File "/usr/local/lib/python3.8/dist-packages/tgarchive/sync.py", line 192, in _get_user
    if u.scam:
AttributeError: 'ChannelForbidden' object has no attribute 'scam'
```

**Comment by zoghal** [comment]
I was able to solve the problem by changing this part of the code
https://github.com/knadh/tg-archive/blob/c410b07859af4e3254bdd5ac65c8200251682202/tgarchive/sync.py#L198
````
    def _get_user(self, u) -> User:
        tags = []

        is_normal_user = isinstance(u, telethon.tl.types.User)
        if isinstance(u, telethon.tl.types.ChannelForbidden):
            return User(
                id=u.id,
                username=u.title,
                first_name=None,
                last_name= None,
                tags=tags,
                avatar= None
            )

        if is_normal_user:
            if u.bot:
                tags.append("bot")
````

**Comment by knadh** [comment]
Thanks. Fixed.
