### ISSUE TITLE
Tried Python 3.10.6

### ISSUE THREAD

**Issue by mbmcclelland** [knadh/tg-archive#77]
Solved: It appears I didn't have pyyaml installed.

I realize this was tested with only python 3.8.6, but I am including the error I saw with 3.10.6 (latest as of 2022-08-03) below if it is helpful:

> K:\3d>C:\Users\username\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip
> Requirement already satisfied: pip in c:\users\username\appdata\local\programs\python\python310\lib\site-packages (22.2.1)
> Collecting pip
>   Downloading pip-22.2.2-py3-none-any.whl (2.0 MB)
>      ---------------------------------------- 2.0/2.0 MB 8.7 MB/s eta 0:00:00
> Installing collected packages: pip
>   Attempting uninstall: pip
>     Found existing installation: pip 22.2.1
>     Uninstalling pip-22.2.1:
>       Successfully uninstalled pip-22.2.1
> Successfully installed pip-22.2.2
> 
> K:\3d>pip3 install tg-archive
> Collecting tg-archive
>   Using cached tg-archive-0.5.5.tar.gz (26 kB)
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [8 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "C:\Users\username\AppData\Local\Temp\pip-install-i705mscv\tg-archive_f4b3fbf3b94c4beeba3144c95be976ab\setup.py", line 5, in <module>
>           from tgarchive import __version__
>         File "C:\Users\username\AppData\Local\Temp\pip-install-i705mscv\tg-archive_f4b3fbf3b94c4beeba3144c95be976ab\tgarchive\__init__.py", line 6, in <module>
>           import yaml
>       ModuleNotFoundError: No module named 'yaml'
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.

**Comment by mbmcclelland** [comment]
It appears I didn't have pyyaml installed
