### ISSUE TITLE
AttributeError: 'Channel' object has no attribute 'bot'

### ISSUE THREAD

**Issue by volyx** [knadh/tg-archive#8]
tg-archive --sync 

It was second run, at first run I entered user tel and code

```
2021-03-24 12:04:10,638: starting Telegram sync (batch_size=2000, limit=0, wait=5)
2021-03-24 12:04:10,655: Connecting to 149.154.167.51:443/TcpFull...
2021-03-24 12:04:10,703: Connection to 149.154.167.51:443/TcpFull complete!
Traceback (most recent call last):
  File "/usr/local/bin/tg-archive", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/tgarchive/__init__.py", line 112, in main
    Sync(cfg, args.session, db.DB(args.data)).sync(args.id)
  File "/usr/local/lib/python3.8/site-packages/tgarchive/sync.py", line 57, in sync
    for m in self._get_messages(self.config["group"],
  File "/usr/local/lib/python3.8/site-packages/tgarchive/sync.py", line 137, in _get_messages
    user=self._get_user(m.sender),
  File "/usr/local/lib/python3.8/site-packages/tgarchive/sync.py", line 143, in _get_user
    if u.bot:
AttributeError: 'Channel' object has no attribute 'bot'
```

**Comment by knadh** [comment]
Ah, it looks like a particular message was sent by a `Channel` and not a `User` entity. Didn't know this was possible. Is the group you are trying to export public? If yes, possible to share a screenshot of the message whose sender is a channel?

In the meanwhile, I can add a check to skip messages that are not sent by `User` entities.

**Comment by volyx** [comment]
> Is the group you are trying to export public?

Yes, it is public channel t.me/javaswag

**Comment by knadh** [comment]
Added the skip: https://github.com/knadh/tg-archive/commit/2259ed7c44b028517da1b96fffb69a7263187040

Can you try the `0.3.1` release? https://pypi.org/project/tg-archive/0.3.1/

**Comment by volyx** [comment]
```
2021-03-24 13:04:18,057: starting Telegram sync (batch_size=2000, limit=0, wait=5)
2021-03-24 13:04:18,074: Connecting to 149.154.167.51:443/TcpFull...
2021-03-24 13:04:18,116: Connection to 149.154.167.51:443/TcpFull complete!
2021-03-24 13:04:22,448: finished. fetched 0 messages. last message = None
```

**Comment by knadh** [comment]
Not sure what's happening here. I'll trying joining the group and syncing and debug.

**Comment by knadh** [comment]
https://pypi.org/project/tg-archive/0.3.2/ adds support for non-User Channel sender.

![image](https://user-images.githubusercontent.com/547147/112333596-c1fbce00-8ce0-11eb-8fac-1c53d2560137.png)
