### ISSUE TITLE
Issues with sqlite3

### ISSUE THREAD

**Issue by 4khil** [knadh/tg-archive#83]
I have upgraded and have the latest sqlite, pip and python - keep getting this error for some reason.
What could be the issue?

2022-09-25 15:37:30,792: fetching from last message id=0 (None)
Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/tg-archive", line 33, in <module>
    sys.exit(load_entry_point('tg-archive==0.5.5', 'console_scripts', 'tg-archive')())
  File "/home/ec2-user/.local/lib/python3.7/site-packages/tgarchive/__init__.py", line 130, in main
    s.sync(args.id, args.from_id)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/tgarchive/sync.py", line 65, in sync
    self.db.insert_user(m.user)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/tgarchive/db.py", line 174, in insert_user
    """, (u.id, u.username, u.first_name, u.last_nam

**Comment by knadh** [comment]
Please share your sqlite version.

> $ python3 -c "import sqlite3; print(sqlite3.sqlite_version)"

**Comment by 4khil** [comment]
3.8.5

**Comment by 4khil** [comment]
When I run 
python3 -c "import sqlite3; print(sqlite3.sqlite_version)"
I get 3.7.17
and when I run sqlite3 --version
I get 3.32.3

Trying to fix this now.

**Comment by 4khil** [comment]
Upgrading sqlite3 in python has been quite an experience, but it's resolved!
Leaving a gist on how to get around to upgrading sqlite3 for Python.

https://gist.github.com/4khil/2189d918f89beaad49ff0972bb631237
