### ISSUE TITLE
AttributeError: 'ChannelForbidden' object has no attribute 'scam'

### ISSUE THREAD

**Issue by Nakilon** [knadh/tg-archive#84]
```
2022-10-22 04:10:57,184: fetching from last message id=96502 (2022-09-23 00:00:00)
Traceback (most recent call last):
  File "/usr/local/bin/tg-archive", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/tgarchive/__init__.py", line 130, in main
    s.sync(args.id, args.from_id)
  File "/usr/local/lib/python3.9/site-packages/tgarchive/sync.py", line 56, in sync
    for m in self._get_messages(group_id,
  File "/usr/local/lib/python3.9/site-packages/tgarchive/sync.py", line 165, in _get_messages
    user=self._get_user(m.sender),
  File "/usr/local/lib/python3.9/site-packages/tgarchive/sync.py", line 192, in _get_user
    if u.scam:
AttributeError: 'ChannelForbidden' object has no attribute 'scam'
```

**Comment by Nakilon** [comment]
Oh I see the https://github.com/knadh/tg-archive/issues/71
How do I use the master branch? I'm not a pythonist. Installed via pip3

**Comment by knadh** [comment]
This fix was released a while ago. You can just upgrade your tg-archive installation to `v1.0.0`.
