### ISSUE TITLE
failed to find libmagic

### ISSUE THREAD

**Issue by sabrysm** [knadh/tg-archive#86]
Although I have installed python-magic I still getting this Error
```BASH 
PS C:\Users\Drakt\Documents\GitHub\test\tg-archive\mysite> tg-archive --build
Traceback (most recent call last):
  File "C:\Users\Drakt\AppData\Local\Programs\Python\Python37\Scripts\tg-archive-script.py", line 11, in <module>
    load_entry_point('tg-archive==1.0.0', 'console_scripts', 'tg-archive')()
  File "C:\Users\Drakt\AppData\Local\Programs\Python\Python37\lib\site-packages\tgarchive\__init__.py", line 152, in main
    from .build import Build
  File "C:\Users\Drakt\AppData\Local\Programs\Python\Python37\lib\site-packages\tgarchive\build.py", line 8, in <module>
    import magic
  File "C:\Users\Drakt\AppData\Local\Programs\Python\Python37\lib\site-packages\magic\__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
  File "C:\Users\Drakt\AppData\Local\Programs\Python\Python37\lib\site-packages\magic\loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

**Comment by sabrysm** [comment]
Problem solved.. I found this to be useful https://github.com/Yelp/elastalert/issues/1927
